### ISSUE TITLE
pub serve generates 404

### ISSUE THREAD

**Issue by Tomucha** [jtmcdole/dart-webgl#6]
Hi! I cloned the repository, moved into created directory and run "pub serve".
After I opened http://localhost:8080/ it generated:

404 Not Found
Could not find asset web in package learn_gl.

If it's not the right way to run this project, please describe the correct way in the README.md ... and if it's the correct way, please fix it :-)

Thanks!

P.S.: Console output:

```
bash-3.2$ pub serve
Loading source assets... 
Serving learn_gl web on http://localhost:8080
Build completed successfully
[web] GET / → Could not find asset learn_gl|web.
```

**Comment by jtmcdole** [comment]
I'm away traveling right now, but I will check this out when I get home. I
wrote this a while ago before 'pub', so it sounds like I need to update a
few things :)

On Tue, Oct 6, 2015 at 6:33 AM, Tomáš Zvěřina <notifications@github.com>
wrote:

> Hi! I cloned the repository, moved into created directory and run "pub
> serve".
> After I opened http://localhost:8080/ it generated:
>
> 404 Not Found
> Could not find asset web in package learn_gl.
>
> If it's not the right way to run this project, please describe the correct
> way in the README.md ... and if it's the correct way, please fix it :-)
>
> Thanks!
>
> P.S.: Console output:
>
> bash-3.2$ pub serve
> Loading source assets...
> Serving learn_gl web on http://localhost:8080
> Build completed successfully
> [web] GET / → Could not find asset learn_gl|web.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jtmcdole/dart-webgl/issues/6>.
>



-- 
John Thomas McDole
jtmcdole@gmail.com
